version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: web.env
    depends_on:
      - db
    volumes:
      - ./:/opt/webapp
    command: gunicorn mailstatic:app --bind 0.0.0.0:5000
  db:
    image: postgres:latest
    env_file: db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
volumes:
  pgdata: